apiVersion: batch/v1
kind: Job
metadata:
  name: cpu
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: cpu
        image: sebmarc/cpu
      restartPolicy: Never