apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: echoserver
    doc: mysite-services-echoserver.html
  name: echoserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echoserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Build {BUILD_VERSION}"
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: echoserver
    spec:
      containers:
      - image: sebmarc/echoserver:{ECHO_VERSION}
        imagePullPolicy: Always
        name: echoservice
        ports:
        - containerPort: 50051
          protocol: TCP
        resources:
          requests:
             cpu: 500m
          limits:
             cpu: 900m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
