apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: echoserver
    doc: mysite-services-echoserver.html
  name: echoserver
  namespace: default
  selfLink: /api/v1/namespaces/default/services/echoserver
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32678
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: echoserver
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.54.108.99